function  SetDefaultGraphicSettings( varargin)
% new colors (0 or 1) - use new Matlab 2014b color scheme?
%SETDEFAULTGRAPHICSETTINGS Summary of this function goes here

set(0, 'DefaultTextInterpreter', 'tex', ...,
'DefaultFigureColor', 'White', ...
 'DefaultFigurePaperType', 'a4letter', ...
 'DefaultAxesColor', 'white', ...
 'DefaultAxesDrawmode', 'fast', ...
 'DefaultAxesFontUnits', 'points', ...
 'DefaultAxesFontSize', 12, ...
 'DefaultAxesFontAngle', 'normal', ...
 'DefaultAxesFontName', 'Times', ...
 'DefaultAxesGridLineStyle', ':', ...
 'DefaultAxesInterruptible', 'on', ...
 'DefaultAxesLayer', 'Bottom', ...
 'DefaultAxesNextPlot', 'replace', ...
 'DefaultAxesUnits', 'normalized', ...
 'DefaultAxesXcolor', [0, 0, 0], ...
 'DefaultAxesYcolor', [0, 0, 0], ...
 'DefaultAxesZcolor', [0, 0, 0], ...
 'DefaultAxesVisible', 'on', ...
 'DefaultLineLineStyle', '-', ...
 'DefaultLineLineWidth', 2, ...
 'DefaultLineMarker', 'none', ...
 'DefaultLineMarkerSize', 11, ...
 'DefaultTextColor', [0, 0, 0], ...
 'DefaultTextFontUnits', 'Points', ...
 'DefaultTextFontSize', 12, ...
 'DefaultTextFontName', 'Times', ...
 'DefaultFigurePaperPositionMode', 'auto');
%  'DefaultTextVerticalAlignment', 'middle', ...
%  'DefaultTextHorizontalAlignment', 'left',...

if ~isempty(varargin)
    new_colors=varargin{1};
    if new_colors==1
        co = [0    0.4470    0.7410; 
            0.8500    0.3250    0.0980; 
            0.9290    0.6940    0.1250; 
            0.4940    0.1840    0.5560; 
            0.4660    0.6740    0.1880; 
            0.3010    0.7450    0.9330; 
            0.6350    0.0780    0.1840]; 
        set(0, 'DefaultFigureColormap',paruly,'DefaultAxesColorOrder',co) 
    elseif new_colors==0
        co = [0 0 1;
          0 0.5 0;
          1 0 0;
          0 0.75 0.75;
          0.75 0 0.75;
          0.75 0.75 0;
          0.25 0.25 0.25];
        set(0,'DefaultFigureColormap',jet,'defaultAxesColorOrder',co)
    else
        error(' input must be 0 or 1 !!!');
    end
end



end

